### ISSUE TITLE
Backend CRUD Operations for Discussion Board Posts

### ISSUE THREAD

**Issue by fzinnah17** [fzinnah17/CodeFM#7]
- [x] Task:

- Define the database schema for discussion posts.
- Develop API endpoints for creating, reading, updating, and deleting posts with proper authentication and authorization checks.

- [ ] Acceptance Criteria:

- Functional CRUD operations for posts on the backend.
- Secure API endpoints that only allow post owners to edit or delete their posts.

Verify:
- Test all CRUD operations for correctness and security.

**Comment by Myesha-Mahazabeen** [comment]
CRUD for discussion board done
